### ISSUE TITLE
insert ads code

### ISSUE THREAD

**Issue by elitetvx** [keesiemeijer/insert-content#1]
Its works for plain text, dont works with google adsense code, any ideas?

**Comment by keesiemeijer** [comment]
Please provide the code so I can test what's going wrong.

**Comment by finex** [comment]
Hi, just put some html code like 

```
<div>something</div>
```

as the string to be inserted, it will not work.

**Comment by keesiemeijer** [comment]
Hi @finex 

Use the insert_element argument if you want to insert a div. By default it inserts paragraphs.
```php
$args = array(
	'insert_element' => 'div'
);

// Insert content is wrapped in a div.
// (You can use other block level HTML tags in this string because it's wrapped in a div)

$insert_content = 'something';
```
