### ISSUE TITLE
Is it possible to insert content after several paragraphs?

### ISSUE THREAD

**Issue by OtherF** [keesiemeijer/insert-content#2]
Hi,

If I want to insert the content after every 3rd paragraph in the text?
Ex.:
```
<p>Paragraph 1</p>
<p>Paragraph 2</p>
<p>Paragraph 3</p>
<p>Inserted content</p>
<p>Paragraph 4</p>
<p>Paragraph 5</p>
<p>Paragraph 6</p>
<p>Inserted content</p>
<p>Paragraph 8</p>
<p>Paragraph 9</p>
<p>Paragraph 10</p>
<p>Inserted content</p>
<p>Paragraph 11</p>
```
Is it possible?

**Comment by keesiemeijer** [comment]
At the moment there's no option to do that. I will add it if I find the time

**Comment by keesiemeijer** [comment]
Try it out with the [develop branch](https://github.com/keesiemeijer/insert-content/tree/develop)

Use the argument `insert_every_p` to have content inserted after every 3rd paragraph.

### Example
```php

$args = array(
	'insert_every_p' => 3,
);

echo keesiemeijer\Insert_Content\insert_content( $content, $insert_content, $args );
```
