### ISSUE TITLE
Problem with HTML encoding

### ISSUE THREAD

**Issue by sansegundo** [keesiemeijer/insert-content#3]
The output comes with problems in enconding special chars like ä ö ü ß etc.

The solution is in --> insert-content.php

line 57:
@$nodes->loadHTML( $content );

change to:
@$nodes->loadHTML( mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8') );

insert (line 49) - this encodes the insert input too
$insert_content = mb_convert_encoding( $insert_content, 'HTML-ENTITIES', 'UTF-8');

**Comment by keesiemeijer** [comment]
Hi @sansegundo 

In the latest version it uses this already.
https://github.com/keesiemeijer/insert-content/blob/master/insert-content.php#L83

It seems I forgot to update the script in the [WP Insert Content](https://github.com/keesiemeijer/wp-insert-content)

Did you mean to put this issue there?

**Comment by sansegundo** [comment]
Yeah, I am using that plugin.

The new version still misses this part

insert (line 49) 
$insert_content = mb_convert_encoding( $insert_content, 'HTML-ENTITIES', 'UTF-8');


I use that one to filter/encode the input I give the plugin to insert from functions.php
Not using your random link :)

**Comment by keesiemeijer** [comment]
I've updated the plugin with the UTF-8 version.

**Comment by sansegundo** [comment]
Great! Thank you.
